codyogden/killedbygoogle

src/components/Item.jsx
=> Add random idioms to products about to be ended.

graveyard.json
=> adding google showtimes

graveyard.json
=> added nexus to the graveyard

graveyard.json
=> Add Jaiku to graveyard

README.md
The key names did not match the format in graveyard.json
=> Fix key names and add more descriptive values

graveyard.json
=> Added Gizmo5 to graveyard.

graveyard.json
Added Google Code Search to graveyard #30
=> Added Google Code Search to graveyard

graveyard.json
Play and Tango started before they ended, this fixes those dates :)
+ small formatting
=> Fix switched close/open dates

graveyard.json
Re issue: #51  - Added Google Catalogs to json file.
=> add google catalogs to graveyard.json file

graveyard.json
Google Sidewiki was a web annotation tool from Google
=> Add Google Sidewiki

graveyard.json
Aardvark was a social search service that connected users live with friends or friends-of-friends who were able to answer their questions.
=> Add Aardvark

graveyard.json
Quick update for hacktoberfest! Love the list you're building. Graveyard file updated with Google Talk (aka 'GChat'), as well as associated information.
There are a few more projects that can be found here as well - if anyone is looking! :) https://en.wikipedia.org/wiki/List_of_Google_products
=> Added Google Talk to graveyard

graveyard.json, graveyard.test.js, package.json
Added a small script to check dates for a positive duration.
=> Add graveyard.test.js for graveyard.json dates

graveyard.json
=> added Google Fast Flip

graveyard.json
It was turned into Google Voice
Please resolve so that BufferBox is not removed.
=> Added Grand Central

graveyard.json
Here is my contribution - Google Glasses
=> Google Glasses

graveyard.json
Nexus player was a digital media player discontinued with no updates
=> Adding Nexus Player

graveyard.json
=> add google directory

graveyard.json
=> add google Friend Connect

.github/ISSUE_TEMPLATE.md, graveyard.json
Added 1 entry to graveyard.json
=> added entry for :Building Maker

.babelrc, .eslintrc, __test__/components/Search.test.jsx, __test__/components/__snapshots__/Search.test.jsx.snap, __test__/jestSetup.js, package.json
Snapshot test and simulating a change in the Search Box.
=> Search component test using Jest and Enzyme

graveyard.json, package.json
- Updated many descriptions for grammar, tense, punctuation, brevity, etc.
- Updated npm scripts to run lint, Jest, and build on test.
=> Description Review & NPM Scripts Update

graveyard.json
This is my first PR for Hacktoberfest. Please have a look. Thanks!
=> Added a project killed by Google.

graveyard.json
=> Fix Project Ara date.

graveyard.json
Changed several incorrect use of an and a.
=> Changed several incorrect use of an and a

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
- Add the Contributing Guide
- Update the PR Template.
=> Add a Contributing Guide

graveyard.json
Correct `dateClose` and adjust description for Pixel C.
=> Update Pixel C

graveyard.json
=> Add Google Currents

graveyard.json
Added Bumptop, tests should pass
=> Added Bumptop

graveyard.json
Hi,
I have created this PR to add the details of Timeful application. 
Thanks :)
=> Added new product - Timeful

graveyard.json
=> added two new products - Google Checkout and Google Pack

graveyard.json
=> Add Google Pixel XL

graveyard.json
Added rebang to the graveyard.json file
=> Added Rebang to graveyard.json

graveyard.json
=> Added a service called REAL ESTATE ON GOOGLE MAPS

graveyard.json
=> Add Google Cloud Connect to the list

graveyard.json
=> Google Hangouts On Air, Google News & Weather and Google Script Converter  service is added.

graveyard.json
=> Added Save to Google Chrome Extension

graveyard.json
Here's one more, killed off by the big G
https://en.wikipedia.org/wiki/Google_Image_Swirl
=> docs(graveyard): Add Google Image Swirl

graveyard.json
=> Added google hands free

graveyard.json
=> Add Freebase to list

graveyard.json
=> Added 'Wildfire Interactive' to Killed by Google List

graveyard.json
I added 'Nexus 5' to 'graveyard.json'.
=> Added 'Nexus 5' to graveyard.json

graveyard.json
=> Added Urchin to the Graveyard

graveyard.json
=> Added Google Send to Phone to graveyard.json

graveyard.json
=> Add Google Flu Trends

graveyard.json
Added 'Nexus 4 Wireless Charger' to Killed by Google List
Added 'Nexus 7' to Killed by Google List
=> Added 'Nexus 4 Wireless Charger' and 'Nexus 7' to Killed by Google List

graveyard.json
=> Added the 3 versions of the Chromebook Pixel

graveyard.json
=> Google Video Player

src/components/Item.jsx
Would it not be more convenient to open link to external source in a new tab ?
=> Open item link in a new tab

graveyard.json
=> Add Songza.

graveyard.json
=> Add Google Chrome Frame. Resolve #199

graveyard.json
=> wrong url Google Chrome Apps

graveyard.json
https://en.wikipedia.org/wiki/Apture
=> Add Apture.

index.html
=> Adjust Twitter Card.

graveyard.json
=> Add Google TV.

graveyard.json
RIP
https://www.blog.google/technology/safety-security/expediting-changes-google-plus/
=> Google+ - April '19 Shut Down

graveyard.json
=> Update Google Allo closing date.

graveyard.json
=> Add Google Refine.

graveyard.json
=> Add Fusion Tables.

index.html
=> Add Bing Meta Tag.

index.html
=> Add Google Meta Tag.

graveyard.json
=> Correct missing types.

graveyard.json
Just a few little additions to make the sentences flow better.
=> Fix a few minor grammatical issues

package.json, yarn.lock
[Issue with Jest and Node 11.11](https://github.com/facebook/create-react-app/issues/6591) resolved with a version upgrade.
=> Upgrade jest to get tests working on travis.

graveyard.json
=> Adjust Google Allo

yarn.lock
=> Upgrade some dependencies.

graveyard.json
Move them both to `2019-04-02`.
=> Adjust Inbox and Google+ death dates.

graveyard.json
=> Added Revolv

src/global.scss
=> Add base text color for dark theme support.

src/index.html
=> People using iFrames to show ads.

graveyard.json
=> Add Android @ Home

graveyard.json
Changed to past tense and extended the description per issue 297's suggestion.
Thanks!
=> Resolve 297, Allo Description Updated

src/App.jsx, src/service-worker.js, webpack.config.js
- The site will now serve the cached content when offline. (#305)
- The caches will be updated when online.
=> Added offline support

graveyard.json
Adds Google Earth Browser Plug-in to graveyard.
I still haven't gotten over it.
=> Add Google Earth Browser Plug-in

graveyard.json
Copy about the integrated amp added from the wikipedia source linked on topic.
=> Issue 278, Nexus Q - Added copy re: amp

CNAME
=> Remove GitHub Pages artifact.

graveyard.json
Hi there!
I added Pixate [pixate.com ](http://pixate.com) #245 to the list.
=> Added Pixate to the list

graveyard.json
Adding some products currently on the issues list.
...and others.
=> Product Additions

src/index.html
=> Add canonical link.

src/index.html
=> Update title tag.

package.json, src/App.jsx
=> Update banner message.

src/App.jsx, src/components/Footer.jsx
Reverts codyogden/killedbygoogle#342
=> Revert "Targets"

yarn.lock
=> Bump eslint-plugin-json. Register lock.

src/index.html
=> Remove iframe force.

src/_headers, webpack.config.js
=> Adjust header rules.

src/App.jsx, src/components/BannerMessage.jsx, src/components/Header.atoms.js, src/components/PressCoverage.jsx, src/components/Search.atoms.js, src/index.html
=> A11y changes, and other styling balances.

src/components/List.jsx
=> Proof copy.

graveyard.json
I added Word Lens to `graveyard.json` to close #325.
=> Add word lens

graveyard.json
Updated the description for Google Now to reflect @codyogden's suggestion in issue #318.
=> Update Google Now Description

graveyard.json
Currently going thru the open issues and updating the graveyard accordingly.
**Current changes**
- Remove Sky Map. #316 
- Add Word Lens. #325 
- Update Google Now Description. #318 
- Add Google Cloud Messaging (GCM). #197
=> Updating graveyard.json

graveyard.json
**Latest Additions:**
- Add Google Hangouts. #217 
- Update Google Play Edition Description. Thank you @Ali-Hirani!
- Add Google Realtime API. #253 
- Add more accurate link than what was suggested.
- Change Google Glass Name to Google Glass Explorer Edition. #302
=> Add More to graveyard.json

package.json, yarn.lock
=> Bump node-sass version.

graveyard.json
Relevant links here:
Launched:
https://africa.googleblog.com/2010/12/google-trader-comes-to-ghana.html
https://www.pambazuka.org/security-icts/ghana-google-trader-launch-stuns-accra
https://www.quora.com/Why-was-Google-Trader-launched-in-Ghana-and-Uganda
Killed:
https://www.google.com.gh/local/trader/
http://web.archive.org/web/20180527072427/https://pctechmag.com/2013/10/google-to-discontinue-google-trader/
https://www.techjaja.com/google-trader-to-be-discontinued-in-favor-of-google-pages21102013/
=> Added an entry for Google Trader

graveyard.json
=> Update Fabric dateClose.

graveyard.json
=> Add Google Jump. Resolve #384.

graveyard.json
=> Recaptcha mailhide

graveyard.json
=> Adjust reCAPTCHA capitalization.

package.json, yarn.lock
- #397 
- #396 
- #395 
- #400 
- #404 
- #407
=> Dependency Upgrades

graveyard.json
=> Add YouTube Gaming.

graveyard.json
Added Google Trips app, after the recent announcement of their plans on moving to google.com/trip.
=> Add Google Trips app

graveyard.json
=> Add Hangouts on Air

package.json, yarn.lock
- Resolve #466
- Resolve #467
- Resolve #468
- Resolve #469
- Resolve #470
- Resolve #471
=> Bump packages from dependabot.

graveyard.json
=> Add Blog Compass.

graveyard.json
h/t Twitter user [jairhart](https://twitter.com/jairhart)
=> Add Follow Your World

.github/workflows/nodejs.yml, .travis.yml, README.md
=> Transition to Github Actions CI

graveyard.json
=> Add Youtube messaging entry

graveyard.json
=> Edit Hangouts Description.

graveyard.json
Sources:
- https://de.wikipedia.org/wiki/Google_Correlate
- https://www.google.com/trends/correlate/
- https://ai.googleblog.com/2012/01/google-correlate-expands-to-49.html
- https://googleblog.blogspot.com/2011/05/mining-patterns-in-search-data-with.html
=> Add Google Correlate.

src/components/Footer.jsx
=> Add email copy to footer.

src/index.html
=> Add og:url

graveyard.json
=> Added YouTube for Nintendo 3DS

graveyard.json
=> Add Google Translator Toolkit

graveyard.json
=> Add YouTube Leanback.

graveyard.json
=> Add G Suite Training/Synergyse

graveyard.json
=> Add Google Bulletin

src/components/Item.jsx
Came across the site for the first time. Had some great ideas that you guys already beat me to so thought I'd add some more end of life idioms. Hope you enjoy!
=> Added End of Life Idioms

graveyard.json
=> Add Google Daydream.

src/components/Item.jsx
=> Fix small spelling error for "Scheduled" in Item.jsx

README.md
Changes to improve Readability of the main README.md, specifically to the text about submitting request or changes for new additions
Particularly relevant in light of Hackoberfest :)
=> Readability Improvements to README

graveyard.json
=> Add Touring Bird.

graveyard.json
=> Add Field Trip

graveyard.json
Physical credit card service that tied to the Google Pay platform.
=> Google Wallet Card

graveyard.json
=> Google related

graveyard.json
=> Dragonfly flavio

graveyard.json
=> Add Google Cloud Print

graveyard.json
=> Update Chromebook Pixel description. Resolves #673

graveyard.json
=> Add One Today.

graveyard.json
https://india.googleblog.com/2020/02/five-years-400-stations-and-thousands.html
=> Google Station Shutdown

graveyard.json
=> Google Material Theme Editor going away

src/components/Footer.tsx
=> Resolves #730

src/App.jsx, src/components/BannerMessage.jsx
=> Add banner message.

graveyard.json
See: https://www.forbes.com/sites/paulmonckton/2020/06/20/google-photos-featue-cancellation-auto-print-selection/#19631af66294
This was a beta program, so I'm unsure if it qualifies for listing, anyhow, here it is :)
=> Add Photo Printing subscription to graveyard

graveyard.json
=> add Focals by North to the graveyard

graveyard.json
=> Added Password Checkup extension

src/App.jsx
=> Remove Banner Message

graveyard.json
=> Add Gesture Search.

graveyard.json
Per:
https://blog.google/products/workspace/latest-google-hangouts-and-upgrade-google-chat/
=> Update Hangouts item.

graveyard.json
=> Trusted contacts

graveyard.json
=> Update Trusted Contacts link.

graveyard.json
=> Add Nest Guard.

graveyard.json
Resolves #777. Update Shoelace description to meet spec.
=> Update Shoelace Description.

graveyard.json
I can't find the exact launch date for this.
=> Add Expeditions

.github/workflows/test.yml
=> Update build and test GA.

pages/index.js
=> Analytics update.

graveyard.json, pages/index.js
=> Transition to Main Branch

pages/index.js
Temp until this is resolved: https://github.com/vercel/next.js/issues/9070
=> Analytics.

graveyard.json
Closes #680. (thanks  @johnvilsack for the information)
=> add Game Builder

graveyard.json
=> Add Google Poly

graveyard.json
=> Add Google Home Max.

graveyard.json
=> Change Password Checkup description.

pages/index.js
=> update social card urls.

graveyard.json
=> fix: reword Android Things entry

graveyard.json
=> Google Short Links

graveyard.json
=> Add Google Cardboard.

graveyard.json
Fixed some typo errors in graveyard
=> Fixed some typo

graveyard.json
Not sure if selected correct branch - https://github.com/codyogden/killedbygoogle/issues/964#issuecomment-876797363
=> Update graveyard.json - Google Commerce Search

components/Filter.jsx, components/List/Item.tsx, components/List/index.js, yarn.lock
These changes address a few errors I noticed in the JS console when running `yarn dev` locally.
=> Development warnings

graveyard.json
=> Remove Google Hangouts. Close #957

graveyard.json
=> Add YouTube Streams. Close #733

graveyard.json
=> Add CallJoy.

graveyard.json
=> Add Tour Builder.

graveyard.json
=> Typo: Earch ➡️ Earth

graveyard.json
=> Remove Cloud Connect Community

graveyard.json
=> Remove Sceneform SDK for Android.

.github/workflows/build.yml, components/App.tsx, components/Filter.tsx, components/Footer/index.tsx, components/Layout.tsx, graveyard.test.ts, package.json, pages/_app.tsx, pages/_document.tsx, pages/index.tsx, tsconfig.json, yarn.lock
- run unit tests in CI
- run TypeScript compilation in CI
- convert test to .ts
- tighten tsconfig (`"strict": true`) and adjust code to comply
I tried to minimize cosmetic changes from editor autoformatting, but there are a few in the build.yml and renamed test file. (by the way, would you be interested in using [prettier](https://prettier.io/))
=> Even more typescript

graveyard.json
=> Add Google Toolbar.

graveyard.json
=> Add Google OnHub

graveyard.json
=> Remove Allo second sentence.

graveyard.json
=> Add Cameos on Google

.github/workflows/graveyard.yml, .github/workflows/playwright.yml, graveyard.json
=> Test GA system

e2e/filter.spec.ts, graveyard.json, playwright.config.ts
Just moving through some quick issues.
=> Closing Issues.

components/List/Item.tsx, components/List/index.tsx
=> feat: Memoize some text to prevent jumping.

.github/workflows/playwright.yml
Specify paths to avoid unnecessary runs.
=> ci(playwright): Specify paths.

graveyard.json
=> feat(graveyard): add Playground AR

graveyard.json
=> feat(graveyard): add Personal Blocklist

graveyard.json
=> feat(graveyard): adSense for mobile

graveyard.json
=> feat(graveyard): add YouTube for PS Vita

graveyard.json
=> feat(graveyard): add YouTube community captions

graveyard.json
=> feat(graveyard): Add Posts on google

README.md
=> docs(README): Remove build status badge.

.github/workflows/graveyard.yml
=> ci: Run graveyard tests when deps are changed.

e2e/search.spec.ts
=> test: Fix search test with different query.

components/Footer/index.tsx
=> Bump copyright year.

graveyard.json
=> Update Google Currents link.

graveyard.json
=> fix(graveyard): angular link

components/List/Item.tsx, components/List/LeadPhrase.tsx, package.json, pages/index.tsx, yarn.lock
=> fix: Resolve hydration error.

.github/workflows/playwright.yml, pages/index.tsx
=> feat(umami): move umami id to env var

next.config.js, pages/_app.tsx
=> feat: proxy analytics.

next.config.js, pages/index.tsx
=> fix: static images.

pages/index.tsx
=> fix: Twitter tag.

graveyard.json
=> Add YouTube Go.

graveyard.json
=> adds conversational actions

graveyard.json
=> Add Android Auto for phone screens

graveyard.json
=> Add Kormo jobs. Resolve #1260.

graveyard.json
=> Add Google Hangouts. Resolve #1256.

graveyard.json
=> Add Google My Business (app)

graveyard.json
=> Update Stadia Entry

graveyard.json
This PR includes a list of grammar-related fixes, including spell-checking, oxford commas, proper pronouns, etc.. as suggested by Grammarly Pro.
I believe the numerous spelling errors fixed within this PR are a necessity.
Examples include:
- "Fitbit Coach was video-based" to "Fitbit Coach was a video-based"
- "synchronise" to "synchronize"
- "motion sensor with embedded microphone" to "motion sensor with an embedded microphone"
- "a RSS feed" to "an RSS feed"
Please feel free to remove any of these edits yourself if you do not like them. I understand that many folks do not use the oxford comma (but you should).
=> Spellchecks

graveyard.json
Change IoT Core link to a more 'neutral' news story than an advertising press-release
r: @QuinnyPig as the original author of this section
=> Link to better news story for IoT core

README.md
=> Remove Twitter badge

graveyard.json
=> adding google surveys

graveyard.json
=> Google Duo

components/List/Item.tsx
1. 49f718ab3fbed58136066ac902f0d350d12a64cf Simplify date processing in `Item.tsx`
2. c59837a2d8466cfa3077224eea4340d32a1c5994 Add title attributes to `<time>` elements ![Screen Shot 2022-10-08 at 22.19.14.png](https://user-images.githubusercontent.com/29367025/194712133-73345ad6-3678-462b-bdcc-746a59ed1580.png)
=> Show full dates in popups

graveyard.json
**What's the Product's Name?**
Build with Chrome
**Describe the product in a single sentence.**
Build with Chrome was a collaboration between Chrome and the LEGO Group that allowed users to build and publish LEGO creations to any digital plot of land in the world through Google Maps.
**When was the product launched? Provide a specific date, if possible.**
January 2014 — The exact date is hard to find, but I believe it was opened to the public on January 28th.
**When was the product discontinued? Provide a specific date, if possible.**
On January 31st, 2017, Build with Chrome would no longer be accepting new submissions. 
**What type of product was it? App, Service, or Hardware?**
Service (I think, it was a website. Correct me if I'm wrong)
=> Build with Chrome

graveyard.json
=> add Polymer

graveyard.json
New entry in graveyard.json + tests passed.
=> Add Google Duplex on the Web.

graveyard.json
New closing date: https://support.google.com/googlenest/answer/11257354?hl=en
=> Update Google Onhub

graveyard.json
=> added ThreadIt

graveyard.json
=> Fix Zeitgeist link.

LICENSE, components/Footer/index.tsx
=> Bump year to 2023

graveyard.json
Resolves #1354.
Closes #1351.
Cloes #1352.
Closes #1353.
=> Add Google Code Jam

graveyard.json
=> Add Grasshopper

graveyard.json
=> Add Jacquard

pages/api/graveyard.ts
enable CORS to all for API requests
=> Enable CORS for API

graveyard.json
Minor improvement to `Bump!`'s description
=> Better Bump! description

graveyard.json
=> Add YouTube Stories

graveyard.json
Exact date of shutting down is yet to be known
=> Add Google Podcasts

graveyard.json
Resolves #1435 
Announcement in Google Blog: https://workspaceupdates.googleblog.com/2023/09/the-next-phase-of-digital-whiteboarding-for-google-workspace.html
=> Add Google Jamboard + Jamboard (device)

graveyard.json
=> Add Pixel Pass

graveyard.json
=> Update Pixel Pass

components/Footer/index.tsx
=> Add Twitter back to footer.

graveyard.json
This PR fixes some descriptions that were not written with past tenses, as to be respectful.
=> Fix some non-past tenses

next.config.js
=> Analytics Changes

pages/_app.tsx
=> Update umami config

graveyard.json
=> Add Dropcam

graveyard.json
=> Fixed a typo in Material Theme Editor

graveyard.json
=> Update Google Podcasts to April 2024

components/Footer/index.tsx
=> copyright year

graveyard.json, yarn.lock
The sunsetting of Keen is announced in this webpage:
=> Add Google Keen

graveyard.json
=> Google One VPN dateClose Update

graveyard.json
Just the PR to add google cache. Hope I did everything correct 😄 
Closes #1480
=> add Google Cache
