graveyard.json

Upon doing some research, I found Google Compare, which they shutdown in 2016.

Added Google Compare to the list

---

graveyard.json

Added an entry for SlickLogin which had a novel concept for "passwordless" logins using uniquely generated sound tokens. It was acquired by Google and they haven't released a commercial product since.

add entry about SlickLogin

---

graveyard.json

https://get.fabric.io/roadmap
> We are integrating the best of Fabric into Firebase to give you one powerful platform. We’ll support Fabric until mid 2019, but we encourage you to migrate to Firebase sooner so you can take advantage of the new tools we are building there.
https://venturebeat.com/2018/09/14/google-is-killing-fabric-in-mid-2019-pushes-developers-to-firebase/

Add `Fabric`

---

graveyard.json

Copy pasta monster got me...
It's just "Fabric". "Tango" pulled from the entry above.
Opps!

Fix `Fabric` name

---

graveyard.json

Google Hotpot was a local recommendation engine that allowed people to rate restaurants, hotels, etc. and share them with friends.

Add Google Hotpot.

---

graveyard.json

Tez was a mobile payments service by Google, targeted at users in India. It was rebranded to Google Pay on August 28, 2018. 
Now it runs as Google Pay, Tez no longer exists.

Add Google Tez 

---

graveyard.json

Google Offers was a service offering discounts and coupons. In 2014, Google announced it would be shutting the service down.

Add Google Offers

---

graveyard.json

Needlebase was purchased by Google in 2011 and discontinued in 2012, the core features being integrated into other projects.
Added to the graveyard.json
#135

added needlebase to graveyard

---

graveyard.json

A service that lasted only a few months. It is not really clear why they took it down.
Funny to note that they kind of recycled the **One** suffix with the rebranding of Google _Drive_ to Google _One_...

Added Google One Pass

---

graveyard.json

Minor fix, this one, but the spacing was not represented correctly for BumpTop.
https://en.wikipedia.org/wiki/BumpTop

fix(graveyard): BumpTop spacing fix

---

graveyard.test.js
package.json

There needs to be a standard way to validate date, and different browsers have differing implementations.
```
Firefox Quantum 63.0 (64-bit)
> new Date("2011-09-31") 
> Invalid Date
Chrome Version 70.0.3538.77 (Official Build) (64-bit)
> new Date("2011-09-31")
> Fri Sep 30 2011 20:00:00 GMT-0400 (Eastern Daylight Time)
```
In both cases, the date is either incorrect, or misrepresented. 
Enter, the moment library. 
It's chunky, yes, but offers a standard implementation for validating date. It's also only needed as a developer dependency.

test: Add moment library for date validation

---

graveyard.json

Added Google Allo as a product that is being killed off by Google. Google announced in April of 2018 that it will pause all development of Google Allo, completely rebranding it as Google Chat. 
#183

Added Google Allo in graveyard.json

---

graveyard.json

See https://en.wikipedia.org/wiki/Google%2B#Shutdown_of_consumer_version

Google+ is not dead yet, but scheduled for august 2019

---

graveyard.json

A bunch of descriptions have missing footstops at the end of their sentence, and they look like this:
So I just add them back.

Add missing footstops

---

graveyard.json

We're doing some cleanup of hardware devices. The general consensus from feedback is that itemized devices aren't needed which have a clear successor (e.g. every Nexus-line phone and tablet model) and will be included as a dead line of hardware in the future.
Certain devices will still be included, for example the Nexus Player which is neither a phone or a tablet.

Cleanup hardware devices.

---

graveyard.json

I was the lead engineer on the project at launch. It was deprecated in December 2006 but was finally shut off in 2009.

Add Google Web APIs (SOAP search)

---

graveyard.json

- Modified "Google Play" to "Google Play Edition" to avoid confusion.

Improve product name of Google Play Edition phones

---

graveyard.json

I'd like to propose that Google X is removed from the graveyard. It seems to have simply undergone a name change and restructuring to a separate business unit. X Development, LLC remains active in similar activities to when it was called Google X. Feedback welcome. Cheers!

remove Google X from graveyard

---

graveyard.json

Added YouTube Video Annotations.
Link included has announcement of service discontinuation.
The Wikipedia page (https://en.wikipedia.org/wiki/Interactive_video#Interactive_video_in_YouTube) doesn't include end date, so I had to go with the Verge.
Start date taken from YouTube announcement here: https://youtube.googleblog.com/2008/06/new-beta-feature-video-annotations.html
Thanks.

Issue 250 - Add Youtube Video Annotations

---

graveyard.json

Removed the Sky Map entry from the graveyard since issue #316 has been open for two weeks.
Sorry for PR #360; still new to them and didn't realize GitHub appends new commits to the same PR if the branches match. This new PR follows better PR etiquette.

Remove Sky Map from Graveyard. Close #316

---

graveyard.json

Source : Google blog
https://gsuiteupdates.googleblog.com/2014/06/removal-of-quickoffice-from-google-play.html

Correct QuickOffice dateClose

---

graveyard.json

I didn't use the link to wikipedia because the page it's not yet updated

Google killed Pixel Slate (graveyard.json update)

---

.github/.github/workflows/stale.yml

I want a better way to clean up the repo with stale Issues.

Add Stale Workflow Actions

---

graveyard.json

Per 9to5Google:
https://9to5google.com/2019/08/21/google-delays-hangouts-death/
Google's Official Death March (Timeline):
https://support.google.com/a/answer/9197126

Update Google Hangouts dateClose.

---

graveyard.json

https://www.androidpolice.com/2019/10/15/google-pulls-first-gen-pixel-buds-daydream-view-and-google-clips-from-its-store/

Add Google Clips.

---

src/App.jsx

escape search term before regex compilation to prevent `Invalid regular expression` exception when entering invalid regex strings into search box. Ex: `*` breaks search box.

escape search term before regex compilation

---

graveyard.json

Fixed a missing word in the Noop description

Fixed a missing word in the Noop description

---

graveyard.json

Ironically Google killed help page too

updated dead URL

---

graveyard.json

RIP https://thenextweb.com/google/2020/04/02/google-is-shutting-down-its-neighbourly-app/

Added neighbourly

---

graveyard.json

They haven't specifically mentioned an end-of-service date, but it's mentioned to be 'before the end of the year' in at least one source:
- https://www.forbes.com/sites/barrycollins/2020/05/13/google-play-music-is-dying-dont-let-it-take-your-mp3-collection-with-it/#728797b145c2

Add Google Play Music to graveyard.json

---

graveyard.json

Due to COVID-19, support for AngularJS 1.x is extended by 6 more months.
See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for the official announcement.

Extended AngularJS until December 31th 2021

---

graveyard.json

to not to be confused with new Google TV chromecast

update google tv link

---

graveyard.json

Updated Google Expeditions to use the english version of wikipedia rather than the German. As much as I love German it is an english speaking site so I would have thought the `link` should be English as well.

Change de to en for Wikipedia Entry

---

graveyard.json

Related to #296 and #628. They've been closed due to being "stale" so I'm getting this entry added.
About date choices:
As is written on Google's own [FAQ page](https://developer.android.com/things/faq), they're taking the whole thing down on 2022-01-05, so I chose this specific date as the final moment for Android Things.
Brillo (announced 2015-05-28) might be considered as its predecessor (and Android Things' codename is still `Brillo`, [per Wikipedia](https://en.wikipedia.org/wiki/Android_Things)) so I chose Brillo's launch date as `dateOpen` instead of 2016-12-13.

Add Android Things' death date

---

graveyard.json

Unclear what best to use as the link for more information. Google has not made the "killed" status clear.  The stackoverflow link includes links and information to other sources.
Supporting Information
- https://developers.google.com/sceneform
- https://github.com/google-ar/sceneform-android-sdk
- https://stackoverflow.com/questions/62453399/google-sceneform-is-it-deprecated-any-replacement
- https://www.reddit.com/r/androiddev/comments/glduwe/is_sceneform_dead/
Date Open
- https://github.com/google-ar/sceneform-android-sdk/releases/tag/v1.0.0
- https://venturebeat.com/2018/05/08/google-debuts-arcore-1-2-with-sceneform-augmented-images-android-and-ios-cloud-anchors/
Date Closed (published a final v1.17.1 release)
- https://mvnrepository.com/artifact/com.google.ar.sceneform/sceneform-base/1 …

Add Sceneform SDK for Android

---

pages/index.js

LinkedIn crawler was using the ad image instead of the designated `og:image` for whatever reason.

Update Page Meta for LinkedIn

---

graveyard.json

Based on the [Chromium blog](https://blog.chromium.org/2020/08/changes-to-chrome-app-support-timeline.html), I would think that the 2022 date applies here. The previous 2021 date is when running Chrome Apps on Windows, macOS, or Linux will require a policy being set. The 2022 date is the final end of support for Chrome Apps.

Use the 2022 date for Google Chrome Apps shutdown

---

graveyard.json

Google haven't out and out said it's dead, but it's been strongly implied by two sources:
[1] https://opensource.googleblog.com/2021/01/the-future-of-tilt-brush.html states that
> Please note that it is not an actively developed product, and no pull requests will be accepted
[2] https://github.com/googlevr/tilt-brush
The repo is up but archived.
--
I don't know if KBG allows products that are being sold but not developed to be considered "killed". Sounds like there is no dev time going into the project at any rate, so I leave this to the maintainers discretion.

Add Tilt Brush

---

graveyard.json

I wasn't able to find the open date (<=2011), using the oldest record in the Wayback Machine.

Google Crisis Map

---

graveyard.json

Developed by Bitspin, this Android application was never significantly updated after Google acquired them in 2014-01. Last updated on 2018-08-09, it does not work properly with Android 10 because it can no longer appear on top of the lock screen and its stopwatch/timer notification updates get frozen.
https://play.google.com/store/apps/details?id=ch.bitspin.timely
End date is the release date of Android 10.

Add Timely Alarm Clock

---

graveyard.json

`dateOpen` was unclear. Articles I've found only reference 2016.

Add Measure.

---

graveyard.json

The following notice is displayed on https://www.google.com/bookmarks/
> After September 30th 2021, Google Bookmarks will no longer be supported.
> To save your bookmarks, click on "Export bookmarks".

Add Google Bookmarks

---

components/Filter.tsx
package.json
yarn.lock

Resolves issues with `react-select` major version migration.

chore(deps): bump react-select from 4.31 to 5.2.1

---

README.md
graveyard.json

Hey Cody!
Long time follower... saw this sad news today. :( 
I wasn't quite sure whether to use 2022-05-01, or 2022-07-01 for the `closeDate`, since both dates are referenced in the linked article from Google. I went with the May date for now... happy to change it to July if you think that's more appropriate.
Cheers,
Ty

Add G Suite legacy free edition

---

.github/workflows/playwright.yml

- Dependabot had no tests running on it.

ci: Run tests when deps change.

---

graveyard.json

July 17th 2018 was the earliest news article about it https://www.engadget.com/2018-07-17-google-assistant-visual-snapshot.html
I couldn't find an official date when it's being shut down so I chose today.
Closes https://github.com/codyogden/killedbygoogle/issues/1172

Add google assistant snapshot

---

graveyard.json

The old date was when Google announced the service was being shut down. The new date is when it was actually removed 
https://9to5google.com/2022/04/13/google-assistant-snapshot-appears-to-finally-sadly-be-gone-for-good/
https://www.androidpolice.com/google-is-killing-snapshot-the-now-replacement-that-never-took-off/#update-2022-04-14-14-13-est-by-will-sattelberg

Fix close date for Google Assistant Snapshot

---

graveyard.json

https://www.theverge.com/2022/9/29/23378713/google-stadia-shutting-down-game-streaming-january-2023
> The service will remain live for players until January 18th, 2023. Google will be refunding all Stadia hardware purchased through the Google Store as well as all the games and add-on content purchased from the Stadia store. Google expects those refunds will be completed in mid-January.
Closes #1286

add google stadia

---

graveyard.json

The link is now dead and need to be changed to a web archive link to view the article it linked it originally.

Updating Google Deskbar Link

---

graveyard.json

Wikipedia has multiple pages named Google TV. Linked directly to the Google Play Movies page.

Fix ambiguous Google TV url

---

graveyard.json

Edits description of YouTube for Nintendo 3DS. Removes "app" to improve grammar and removes mention of alternate 3DS models.

Simplify YouTube 3DS description

---

graveyard.json

Resolve #1316 
Adds Google Street View app to the list of killed google products.

Google Street View app

---

graveyard.json

https://9to5google.com/2023/06/15/google-domains-squarespace/
https://newsroom.squarespace.com/blog/googledomains

Add Google Domains

---

graveyard.json

The open date is from https://www.androidpolice.com/2016/08/01/psa-google-album-archive-shows-photo-albums-one-place/
> [According to Google's Luke Wroblewski](https://plus.google.com/+LukeWroblewski/posts/TonQQqMqvAj), Album Archive finished rolling out to everyone on August 5

Add Google Album Archive

---

graveyard.json

The link to source for Google grasshopper was a link from Google grasshopper's website. Their website has now been taken down. This link also did not abide by guidelines, "Please do not use Google Support articles, linking to the product's URL, the product's marketing URL, or other Google-provided links". I updated it with an android police link that conveys the same message.

Fix Google Grasshopper link

---

bin/kill

Updates the `yarn kill` command to respect the user's confirmation and only update the graveyard if the user confirms that.

/bin/kill: respect user confirmation

---

graveyard.json

Found out [via Techcrunch](https://techcrunch.com/2025/09/11/google-is-shutting-down-tables-its-airtable-rival/) earlier today. Google's FAQ is [here](https://support.google.com/area120-tables/answer/10831919).
The FAQ is also linked from the warning banner at Tables' homepage:
I guess #1595 was prescient.

Add Tables by Area 120, to be discontinued 2025-12-16
